from com import NingBo
me =  NingBo.NingBo('chenyuwen', 'wen960803')
#me.daoW()
#me.sM()
me.login()
#me.startX()
#me.daoW1()
#me.sM()
# me.startProPlan()
# me.danger()
# me.tongD()
# me.startProPlan()
# me.offPro()
# me.jianX()
# me.offJianX()
#me.endX()
me.test()
#input("请按回车键退出")